### ISSUE TITLE
Setup prettier, eslint, husky

### ISSUE THREAD

**Issue by bogas04** [probot/first-timers-only-app#5]
It'll be nice to setup [prettier](https://prettier.io/) & [eslint](https://eslint.org/) to avoid formatting and linting issues. 
You can add the same in your `test` script to ensure it breaks on such issues.

Lastly, you may add [husky](https://www.npmjs.com/package/husky) to add a `prepush` script that runs the test on the contributors machine before pushing. This would block broken code as early as possible. 

Let me know if you need help with the same.

**Comment by aps120797** [comment]
Hey @bogas04 , I think Probot follows [standard](https://standardjs.com/) for it's linting.
Thanks for letting me know about husky, it's something that I really needed. 😄
